// <auto-generated />
namespace Erp_express.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createPermission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createPermission));
        
        string IMigrationMetadata.Id
        {
            get { return "202404210316098_createPermission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
